# Generated by Django 6.0.1 on 2026-01-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('identity_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='employees.employee')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.sector')),
            ],
        ),
    ]
