# Generated by Django 6.0.1 on 2026-01-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('diploma', 'Diploma'), ('course', 'Course')], max_length=20)),
                ('duration_months', models.IntegerField()),
            ],
        ),
    ]
